[package]
name = "rust-database-2"
version = "0.1.0"
authors = ["Adam Casey <acasey23@bloomberg.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
